
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/pierrec/xxHash"

[[constraint]]
  branch = "master"
  name = "github.com/pmezard/go-difflib"

[[constraint]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[constraint]]
  branch = "master"
  name = "github.com/eapache/go-resiliency"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.15.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.60"

[[constraint]]
  branch = "master"
  name = "github.com/carlescere/scheduler"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-coap"

[[constraint]]
  branch = "master"
  name = "github.com/eawsy/aws-lambda-go-core"

[[constraint]]
  branch = "master"
  name = "github.com/eclipse/paho.mqtt.golang"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[constraint]]
  branch = "master"
  name = "github.com/japm/goScript"

[[constraint]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[[constraint]]
  branch = "master"
  name = "github.com/sfreiberg/gotwilio"

[[constraint]]
  name = "github.com/stianeikeland/go-rpio"
  version = "4.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/tensorflow/tensorflow"
  version = "=1.4.1"

[[constraint]]
  name = "gopkg.in/couchbase/gocb.v1"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/mongodb/mongo-go-driver"
