// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/tensor.proto

/*
Package tensorflow is a generated protocol buffer package.

It is generated from these files:
	tensorflow/core/framework/tensor.proto

It has these top-level messages:
	TensorProto
	VariantTensorDataProto
*/
package tffw

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Protocol buffer representing a tensor.
type TensorProto struct {
	Dtype DataType `protobuf:"varint,1,opt,name=dtype,enum=tensorflow.DataType" json:"dtype,omitempty"`
	// Shape of the tensor.  TODO(touts): sort out the 0-rank issues.
	TensorShape *TensorShapeProto `protobuf:"bytes,2,opt,name=tensor_shape,json=tensorShape" json:"tensor_shape,omitempty"`
	// Version number.
	//
	// In version 0, if the "repeated xxx" representations contain only one
	// element, that element is repeated to fill the shape.  This makes it easy
	// to represent a constant Tensor with a single value.
	VersionNumber int32 `protobuf:"varint,3,opt,name=version_number,json=versionNumber" json:"version_number,omitempty"`
	// Serialized raw tensor content from either Tensor::AsProtoTensorContent or
	// memcpy in tensorflow::grpc::EncodeTensorToByteBuffer. This representation
	// can be used for all tensor types. The purpose of this representation is to
	// reduce serialization overhead during RPC call by avoiding serialization of
	// many repeated small items.
	TensorContent []byte `protobuf:"bytes,4,opt,name=tensor_content,json=tensorContent,proto3" json:"tensor_content,omitempty"`
	// DT_HALF. Note that since protobuf has no int16 type, we'll have some
	// pointless zero padding for each value here.
	HalfVal []int32 `protobuf:"varint,13,rep,packed,name=half_val,json=halfVal" json:"half_val,omitempty"`
	// DT_FLOAT.
	FloatVal []float32 `protobuf:"fixed32,5,rep,packed,name=float_val,json=floatVal" json:"float_val,omitempty"`
	// DT_DOUBLE.
	DoubleVal []float64 `protobuf:"fixed64,6,rep,packed,name=double_val,json=doubleVal" json:"double_val,omitempty"`
	// DT_INT32, DT_INT16, DT_INT8, DT_UINT8.
	IntVal []int32 `protobuf:"varint,7,rep,packed,name=int_val,json=intVal" json:"int_val,omitempty"`
	// DT_STRING
	StringVal [][]byte `protobuf:"bytes,8,rep,name=string_val,json=stringVal,proto3" json:"string_val,omitempty"`
	// DT_COMPLEX64. scomplex_val(2*i) and scomplex_val(2*i+1) are real
	// and imaginary parts of i-th single precision complex.
	ScomplexVal []float32 `protobuf:"fixed32,9,rep,packed,name=scomplex_val,json=scomplexVal" json:"scomplex_val,omitempty"`
	// DT_INT64
	Int64Val []int64 `protobuf:"varint,10,rep,packed,name=int64_val,json=int64Val" json:"int64_val,omitempty"`
	// DT_BOOL
	BoolVal []bool `protobuf:"varint,11,rep,packed,name=bool_val,json=boolVal" json:"bool_val,omitempty"`
	// DT_COMPLEX128. dcomplex_val(2*i) and dcomplex_val(2*i+1) are real
	// and imaginary parts of i-th double precision complex.
	DcomplexVal []float64 `protobuf:"fixed64,12,rep,packed,name=dcomplex_val,json=dcomplexVal" json:"dcomplex_val,omitempty"`
	// DT_RESOURCE
	ResourceHandleVal []*ResourceHandleProto `protobuf:"bytes,14,rep,name=resource_handle_val,json=resourceHandleVal" json:"resource_handle_val,omitempty"`
	// DT_VARIANT
	VariantVal []*VariantTensorDataProto `protobuf:"bytes,15,rep,name=variant_val,json=variantVal" json:"variant_val,omitempty"`
}

func (m *TensorProto) Reset()                    { *m = TensorProto{} }
func (m *TensorProto) String() string            { return proto.CompactTextString(m) }
func (*TensorProto) ProtoMessage()               {}
func (*TensorProto) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *TensorProto) GetDtype() DataType {
	if m != nil {
		return m.Dtype
	}
	return DataType_DT_INVALID
}

func (m *TensorProto) GetTensorShape() *TensorShapeProto {
	if m != nil {
		return m.TensorShape
	}
	return nil
}

func (m *TensorProto) GetVersionNumber() int32 {
	if m != nil {
		return m.VersionNumber
	}
	return 0
}

func (m *TensorProto) GetTensorContent() []byte {
	if m != nil {
		return m.TensorContent
	}
	return nil
}

func (m *TensorProto) GetHalfVal() []int32 {
	if m != nil {
		return m.HalfVal
	}
	return nil
}

func (m *TensorProto) GetFloatVal() []float32 {
	if m != nil {
		return m.FloatVal
	}
	return nil
}

func (m *TensorProto) GetDoubleVal() []float64 {
	if m != nil {
		return m.DoubleVal
	}
	return nil
}

func (m *TensorProto) GetIntVal() []int32 {
	if m != nil {
		return m.IntVal
	}
	return nil
}

func (m *TensorProto) GetStringVal() [][]byte {
	if m != nil {
		return m.StringVal
	}
	return nil
}

func (m *TensorProto) GetScomplexVal() []float32 {
	if m != nil {
		return m.ScomplexVal
	}
	return nil
}

func (m *TensorProto) GetInt64Val() []int64 {
	if m != nil {
		return m.Int64Val
	}
	return nil
}

func (m *TensorProto) GetBoolVal() []bool {
	if m != nil {
		return m.BoolVal
	}
	return nil
}

func (m *TensorProto) GetDcomplexVal() []float64 {
	if m != nil {
		return m.DcomplexVal
	}
	return nil
}

func (m *TensorProto) GetResourceHandleVal() []*ResourceHandleProto {
	if m != nil {
		return m.ResourceHandleVal
	}
	return nil
}

func (m *TensorProto) GetVariantVal() []*VariantTensorDataProto {
	if m != nil {
		return m.VariantVal
	}
	return nil
}

// Protocol buffer representing the serialization format of DT_VARIANT tensors.
type VariantTensorDataProto struct {
	// Name of the type of objects being serialized.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	// Portions of the object that are not Tensors.
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Tensors contained within objects being serialized.
	Tensors []*TensorProto `protobuf:"bytes,3,rep,name=tensors" json:"tensors,omitempty"`
}

func (m *VariantTensorDataProto) Reset()                    { *m = VariantTensorDataProto{} }
func (m *VariantTensorDataProto) String() string            { return proto.CompactTextString(m) }
func (*VariantTensorDataProto) ProtoMessage()               {}
func (*VariantTensorDataProto) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *VariantTensorDataProto) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *VariantTensorDataProto) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VariantTensorDataProto) GetTensors() []*TensorProto {
	if m != nil {
		return m.Tensors
	}
	return nil
}

func init() {
	proto.RegisterType((*TensorProto)(nil), "tensorflow.TensorProto")
	proto.RegisterType((*VariantTensorDataProto)(nil), "tensorflow.VariantTensorDataProto")
}

func init() { proto.RegisterFile("tensorflow/core/framework/tensor.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x5f, 0x8f, 0xd2, 0x40,
	0x14, 0xc5, 0x33, 0x5b, 0x59, 0xda, 0xdb, 0x82, 0x5a, 0x8d, 0x36, 0xac, 0x9b, 0x1d, 0x49, 0x30,
	0x13, 0xa3, 0x10, 0xd1, 0xf8, 0x6a, 0xc2, 0xfa, 0xe0, 0xd3, 0xba, 0xa9, 0x1b, 0x5e, 0xc9, 0x40,
	0x87, 0xa5, 0xb1, 0x9d, 0x21, 0xd3, 0x81, 0x75, 0xdf, 0x7d, 0xf3, 0x0b, 0xfb, 0x68, 0xe6, 0x4e,
	0x81, 0xfa, 0xff, 0x91, 0x73, 0x7e, 0xf7, 0x9c, 0x5b, 0x7a, 0x0b, 0xcf, 0x8c, 0x90, 0x95, 0xd2,
	0xcb, 0x42, 0xdd, 0x8c, 0x16, 0x4a, 0x8b, 0xd1, 0x52, 0xf3, 0x52, 0xdc, 0x28, 0xfd, 0x79, 0xe4,
	0x9c, 0xe1, 0x5a, 0x2b, 0xa3, 0x62, 0x38, 0x70, 0xbd, 0xd1, 0xdf, 0x67, 0xb4, 0xa8, 0xd4, 0x46,
	0x2f, 0xc4, 0x6c, 0xc5, 0x65, 0x56, 0x08, 0x37, 0xdc, 0x7b, 0xf1, 0xbf, 0x92, 0x59, 0xb5, 0xe2,
	0xeb, 0x1d, 0x3d, 0xf8, 0x07, 0x7d, 0xbb, 0x16, 0x95, 0xc3, 0xfa, 0xdf, 0x5a, 0x10, 0x5e, 0x21,
	0x79, 0x89, 0x1b, 0x3e, 0x87, 0x56, 0x66, 0xfd, 0x84, 0x50, 0xc2, 0xba, 0xe3, 0x87, 0xc3, 0x43,
	0xcc, 0xf0, 0x3d, 0x37, 0xfc, 0xea, 0x76, 0x2d, 0x52, 0x87, 0xc4, 0xef, 0x20, 0x6a, 0x16, 0x27,
	0x47, 0x94, 0xb0, 0x70, 0xfc, 0xa4, 0x39, 0xe2, 0xa2, 0x3f, 0x59, 0x1b, 0xf3, 0xd3, 0xd0, 0x1c,
	0x94, 0x78, 0x00, 0xdd, 0xad, 0xd0, 0x55, 0xae, 0xe4, 0x4c, 0x6e, 0xca, 0xb9, 0xd0, 0x89, 0x47,
	0x09, 0x6b, 0xa5, 0x9d, 0x5a, 0xbd, 0x40, 0xd1, 0x62, 0x75, 0xcf, 0x42, 0x49, 0x23, 0xa4, 0x49,
	0xee, 0x50, 0xc2, 0xa2, 0xb4, 0xe3, 0xd4, 0x73, 0x27, 0xc6, 0xa7, 0xe0, 0xaf, 0x78, 0xb1, 0x9c,
	0x6d, 0x79, 0x91, 0x74, 0xa8, 0xc7, 0x5a, 0x93, 0xa3, 0x7b, 0x24, 0x6d, 0x5b, 0x6d, 0xca, 0x8b,
	0xf8, 0x0c, 0x82, 0x65, 0xa1, 0xb8, 0x41, 0xbf, 0x45, 0x3d, 0x76, 0x84, 0xbe, 0x8f, 0xa2, 0x05,
	0x9e, 0x02, 0x64, 0x6a, 0x33, 0x2f, 0x04, 0x12, 0xc7, 0xd4, 0x63, 0x04, 0x89, 0xc0, 0xa9, 0x16,
	0x39, 0x81, 0x76, 0x2e, 0x5d, 0x42, 0x7b, 0xdf, 0x70, 0x9c, 0x4b, 0x9c, 0x3f, 0x05, 0xa8, 0x8c,
	0xce, 0xe5, 0x35, 0xfa, 0x3e, 0xf5, 0x58, 0x94, 0x06, 0x4e, 0xb1, 0xf6, 0x00, 0xa2, 0x6a, 0xa1,
	0xca, 0x75, 0x21, 0xbe, 0x20, 0x10, 0xec, 0x57, 0x08, 0x77, 0x7a, 0xbd, 0x66, 0x2e, 0xcd, 0xdb,
	0x37, 0xc8, 0x00, 0xf5, 0x98, 0xe7, 0xd6, 0x44, 0xd1, 0xd5, 0xf8, 0x73, 0xa5, 0x0a, 0xf4, 0x43,
	0xea, 0x31, 0xdf, 0x3d, 0xa6, 0xd5, 0xea, 0x9a, 0xac, 0x59, 0x13, 0xed, 0x9f, 0x23, 0xcc, 0x1a,
	0x35, 0x1f, 0xe1, 0xc1, 0x2f, 0x57, 0x86, 0x74, 0x97, 0x7a, 0x2c, 0x1c, 0x9f, 0x35, 0x5f, 0x61,
	0x5a, 0x63, 0x1f, 0x90, 0x72, 0x6f, 0xf1, 0xbe, 0xfe, 0x49, 0xb4, 0x81, 0xe7, 0x10, 0x6e, 0xb9,
	0xce, 0x79, 0xfd, 0xf7, 0xdc, 0xc5, 0xa0, 0x7e, 0x33, 0x68, 0xea, 0x6c, 0x77, 0x12, 0xf6, 0x96,
	0x5c, 0x16, 0xd4, 0x63, 0x53, 0x5e, 0xf4, 0xbf, 0x12, 0x78, 0xf4, 0x67, 0x2c, 0x3e, 0x81, 0xc0,
	0x1e, 0xdd, 0x4c, 0xf2, 0xd2, 0x1d, 0x67, 0x90, 0xfa, 0x56, 0xb8, 0xe0, 0xa5, 0x88, 0x7b, 0xe0,
	0x97, 0xc2, 0xf0, 0x8c, 0x1b, 0x8e, 0x57, 0x18, 0xa5, 0xfb, 0xdf, 0xf1, 0x2b, 0x68, 0xbb, 0x25,
	0xaa, 0xc4, 0xc3, 0xa5, 0x1e, 0xff, 0x7e, 0xa0, 0x6e, 0x93, 0x1d, 0x37, 0x79, 0x09, 0x89, 0xd2,
	0xd7, 0x4d, 0x6c, 0xff, 0xf1, 0x4c, 0xa2, 0xc6, 0x44, 0x75, 0x49, 0xbe, 0x13, 0x32, 0x3f, 0xc6,
	0x4f, 0xe9, 0xf5, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0xb4, 0x29, 0xf5, 0x06, 0x04, 0x00,
	0x00,
}
